config/routes.rb
Rails.application.routes.draw do

  root 'goodsmarkets#index'
  get 'goodsmarkets/index'
  get 'goodsmarkets/customer'
  post '/csignin'=>'goodsmarkets#csignin', as: 'csignin'
  get 'goodsmarkets/manufacturer'
  post '/msignin'=>'goodsmarkets#msignin',  as: 'msignin'
  get 'mfrs/logout'=>'mfrs#logout', as: 'mlogout'
  get 'mfrs/profile'=>'mfrs#profile', as: 'mprofile'
  get 'custs/logout'=>'custs#logout', as: 'clogout'
  get 'custs/profile'=>'custs#profile', as: 'cprofile'
  post 'custs/search'=>'custs#search', as: 'search'
  get 'cproducts/ratings'=>'cproducts#ratings',as:'ratings'
  get 'cproducts/cart'=>'cproducts#cart',as:'cart'
  get 'cproducts/payment'=>'cproducts#payment',as:'payment'
  get 'cproducts/order'=>'cproducts#order',as:'order'
  get 'orders/confirm'=>'orders#confirm'
  get 'orders/cancel'=>'orders#cancel'
  get 'orders/show'=>'orders#show'
  get 'orders/shipped'=>'orders#shipped'
  get 'orders/delivered'=>'orders#delivered'
  get 'orders/packed'=>'orders#packed'
  get 'orders/forcecancel'=>'orders#forcecancel'
  # get 'mhomes/logout'=>'mhomes#logout', as: 'mlogout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :mfrs do
    resources :mproducts
  end
  resources :custs
  resources :cproducts
#   if Rails.env.production?
#     get '404', :to => 'application#page_not_found'
#  end
end

app/models/cust.rb
class Cust < ApplicationRecord
    validates :username,presence: true
    validates :password,presence: true
    validates :email,presence: true,uniqueness: true,format: { with: /\A[A-Za-z][A-Za-z0-9]+@[A-Za-z0-9]+\.[a-z]{2,3}\z/ }
    validates :mobile_no,presence: true,numericality: {onlt_integer:true},length: {is: 10}
    validates :address,presence: true
end

app/controllers/custs_controller.rb
class CustsController < ApplicationController
  skip_before_filter :verify_login ,only: [:new,:create]
    def index
      @cust = Cust.find(@cid)
      if session[:group].nil?||session[:group]==""
        @search=Mproduct.all 
      else
        @search= Mproduct.where(group: session[:group])
      end
    end
    def search 
      session[:group] = params[:mproducts][:group]
      redirect_to custs_path
    end
    def  new
        @cust = Cust.new
    end
    def create
        @cust = Cust.new(credentials)
        if @cust.save
          session[:cid]=Cust.find_by(email: @cust.email).id
          redirect_to custs_path,notice: "Customer Registered"
        else
          render 'new'
        end
    end
    def profile
      @cust=Cust.find(@cid)
    end
    def edit
      @cust=Cust.find(@cid)
    end
    def update 
      @cust=Cust.find(@cid)
      if @cust.update(credentials)
        redirect_to cprofile_path,notice: "Updated Sucessfully"
      else
        render 'edit'
      end
    end
    def logout
      session.delete(:cid)
      redirect_to root_path,notice: "loggedout #{@e} successfully "
    end
    def destroy
      @cust=Cust.find(@cid)
      @e="and Removed"
      @cust.destroy
      logout
    end
    private
    def credentials
      params.require(:cust).permit(:username,:email,:password,:mobile_no,:address)
    end
end

app/helpers/custs_helper.rb
module CustsHelper
end

app/views/custs/edit.html.erb
<h2> Edit your Profile </h2>

<%= form_for :cust, url: cust_path(@cid),method: :patch do |f| %>
<%@cust.errors.full_messages.each do |msg|%>
 <div class="alert alert-danger "><%=msg%></div>
<%end%>
<div class="form-group ">	
		<div class="col-xs-1">
			<%= f.label :username %>
		</div>
		<div class="col-xs-2">
			<%= f.text_field :username ,class:"form-control "%>
		</div>
	</div>
	<br/>
	<br/>
	<div class="form-group">
		<div class="col-xs-1">
			<%= f.label :email %>
		</div>
		<div class="col-xs-2">
			<%= f.text_field :email ,class:"form-control"%></td>
		</div>
	</div>
	<br/>
    <div class="form-group ">	
		<div class="col-xs-1">
			<%= f.label :password %>
		</div>
		<div class="col-xs-2">
			<%= f.password_field :password ,class:"form-control "%>
		</div>
	</div>
	<br/>
    <div class="form-group">
		<div class="col-xs-1">
			<%= f.label :mobile_no %>
		</div>
		<div class="col-xs-2">
			<%= f.text_field :mobile_no ,class:"form-control "%></td>
		</div>
	</div>
    <br/>
    <div class="form-group ">	
		<div class="col-xs-1">
			<%= f.label :address %>
		</div>
		<div class="col-xs-2">
			<%= f.text_area :address ,class:"form-control "%>
		</div>
	</div>
	<br/>
    <br/>
	<br/>
	<br/>
	<div class="col-xs-2">
		<%= f.submit 'Save' ,class: "btn btn-primary "%>
		<%= link_to "cancel" ,cprofile_path,class: "btn btn-primary"%>
</div>
	<%end%>

app/views/custs/index.html.erb
<h1>welcome <%= @cust.username%></h1>
<div class="container-fluid">
<br/>
<%= link_to "Home", custs_path ,class:"btn btn-info"%>
<%= link_to "Profile", cprofile_path ,class:"btn btn-info"%>
<%= link_to "cart",cart_path,class: "btn btn-info"%>
<%= link_to "Placed",orders_show_path(status: "Placed"),class: "btn btn-info"%>
<%= link_to "History",orders_show_path,class: "btn btn-info"%>
<%= link_to "logout", clogout_path ,class:"btn btn-danger"%>
</div>
<br/>
<br/>


<%= form_for :mproducts, url: search_path,method: :index do |f| %>
<div class="form-group row">	
	<div class="col-xs-1">
		<%= f.label :Product %>
	</div>
	<div class="col-xs-9">
		<%= f.text_field :group ,class:"form-control",placeholder:"Search by Product Group"%>
	</div>
    <div class="col-xs-2">
	<%= f.submit 'Search' ,class: "btn btn-primary "%>
    </div>
</div>
<%end%>


<h2> Product Available </h2>
<% @search.each do |p|%>
<div class="col-sm-3 ">
    <div class="container-fluid bg-info ">
        <h3 class="text-center"><%=p.product_name%></h3>
        <br/>
        <h5 class="text-left col-sm-5">Price : &#8377;<%=p.price%></h5>
        <h5 class="text-right col-sm-7">Ratings : &#10031;<%=p.ratings%></h5>
        <h5 class="text-left col-sm-8">Manufacturer : <%=p.mfr_id%> <%=Mfr.find(p.mfr_id).username%> </h5>
        <%= link_to "View",cproducts_path(mid: p.mfr_id,pid: p.pid),class: "btn btn-primary col-sm-4"%>
        <h5 class="text-left col-sm-7">Available : <%=p.quantity%></h5>
        <%= link_to "Add to cart",new_cproduct_path(pid:p.pid,pname:p.product_name),class: "btn btn-primary col-sm-5"%>
        
    </div>
</div>

<% end%>


app/views/custs/new.html.erb
<h2> Welcome New Customer </h2>

<%= form_for :cust, url: custs_path do |f| %>
<%@cust.errors.full_messages.each do |msg|%>
 <div class="alert alert-danger "><%=msg%></div>
<%end%>
<div class="form-group ">	
	<div class="col-xs-1">
		<%= f.label :username %>
	</div>
	<div class="col-xs-2">
		<%= f.text_field :username ,class:"form-control "%>
	</div>
</div>
<br/>
<br/>
<div class="form-group">
	<div class="col-xs-1">
		<%= f.label :email %>
	</div>
	<div class="col-xs-2">
		<%= f.text_field :email ,class:"form-control"%></td>
	</div>
</div>
<br/>
<div class="form-group ">	
	<div class="col-xs-1">
		<%= f.label :password %>
	</div>
	<div class="col-xs-2">
		<%= f.password_field :password ,class:"form-control "%>
	</div>
</div>
<br/>
<div class="form-group">
	<div class="col-xs-1">
		<%= f.label :mobile_no %>
	</div>
	<div class="col-xs-2">
		<%= f.text_field :mobile_no ,class:"form-control "%></td>
	</div>
</div>
<br/>
<div class="form-group ">	
	<div class="col-xs-1">
		<%= f.label :address %>
	</div>
	<div class="col-xs-2">
		<%= f.text_area :address ,class:"form-control "%>
	</div>
</div>
<br/>
<br/>
<br/>
<br/>
<div class="col-xs-2">
	<%= f.submit 'Save' ,class: "btn btn-primary "%>
	<%= link_to "cancel" ,goodsmarkets_customer_path,class: "btn btn-primary"%>
</div>
<%end%>

app/views/custs/profile.html.erb
<h2>Profile</h2>

<table class="table">
    <tbody>
    <tr class="">
      <th class="col-sm-1">User Id</th>
      <td class="col-sm-1"><%= @cid %></td>
    </tr>
    <tr class="">
      <th class="col-sm-1">Username</th>
      <td class="col-sm-1"><%= @cust.username %></td>
    </tr>
     <tr class="">
      <th class="col-sm-1">Email id</th>
      <td class="col-sm-1"><%= @cust.email %></td>
    </tr>
     <tr class="">
      <th class="col-sm-1">Mobile number</th>
      <td class="col-sm-1"><%= @cust.mobile_no %></td>
    </tr>
    <tr class="">
      <th class="col-sm-1">Address</th>
      <td class="col-sm-1"><%= @cust.address %></td>
    </tr>
    </tbody>
</table>


<%= link_to "Edit" ,edit_cust_path(@cid),class: "btn btn-primary"%>
<%= link_to 'Home',custs_path ,class: "btn btn-primary"%>

<%= link_to "Delete Account" ,cust_path(@cid),method: :delete,data:{confirm:"confirm to Delete Account \nonce Deleted it cant be retrived!!!!!"},class: "btn btn-danger"%>