config/routes.rb
Rails.application.routes.draw do

  root 'goodsmarkets#index'
  get 'goodsmarkets/index'
  get 'goodsmarkets/customer'
  post '/csignin'=>'goodsmarkets#csignin', as: 'csignin'
  get 'goodsmarkets/manufacturer'
  post '/msignin'=>'goodsmarkets#msignin',  as: 'msignin'
  get 'mfrs/logout'=>'mfrs#logout', as: 'mlogout'
  get 'mfrs/profile'=>'mfrs#profile', as: 'mprofile'
  get 'custs/logout'=>'custs#logout', as: 'clogout'
  get 'custs/profile'=>'custs#profile', as: 'cprofile'
  post 'custs/search'=>'custs#search', as: 'search'
  get 'cproducts/ratings'=>'cproducts#ratings',as:'ratings'
  get 'cproducts/cart'=>'cproducts#cart',as:'cart'
  get 'cproducts/payment'=>'cproducts#payment',as:'payment'
  get 'cproducts/order'=>'cproducts#order',as:'order'
  get 'orders/confirm'=>'orders#confirm'
  get 'orders/cancel'=>'orders#cancel'
  get 'orders/show'=>'orders#show'
  get 'orders/shipped'=>'orders#shipped'
  get 'orders/delivered'=>'orders#delivered'
  get 'orders/packed'=>'orders#packed'
  get 'orders/forcecancel'=>'orders#forcecancel'
  # get 'mhomes/logout'=>'mhomes#logout', as: 'mlogout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :mfrs do
    resources :mproducts
  end
  resources :custs
  resources :cproducts
#   if Rails.env.production?
#     get '404', :to => 'application#page_not_found'
#  end
end

app/models/cproduct.rb
class Cproduct < ApplicationRecord
    # belongs_to :mproducts
    validates :pid,presence: true
    validates :pname,presence: true
    validates :quantity,presence: true
end

app/controllers/cproducts_controller.rb
class CproductsController < ApplicationController
    def index
        @product=Mproduct.find_by(mfr_id:params[:mid],pid:params[:pid])
        @samemfr=Mproduct.where(mfr_id:params[:mid])
    end

    def ratings
        @product=Mproduct.find_by(mfr_id:params[:mid],pid:params[:pid])
        @product.ratings+=params[:number].to_i
        @product.rcount+=1
        if @product.save
            redirect_to cproducts_path(mid:params[:mid],pid:params[:pid]) 
        end
    end

    def new
        session[:pname]=params[:pname]
        session[:pid]=params[:pid]
        unless Cproduct.find_by(pid:session[:pid],cust_id: session[:cid],status: "Cart")
                @cart=Cproduct.new
        else
             redirect_to edit_cproduct_path(session[:pid])
        end
    end

    def create 
         unless Cproduct.find_by(pid:session[:pid],cust_id: session[:cid],status: "Cart")
            @cart=Cproduct.new(product_creds)
            @cart.cust_id=session[:cid]
            if @cart.save
                redirect_to custs_path,notice: "Added to cart"
            else 
                render 'new'
            end
         else
             redirect_to edit_cproduct_path(session[:pid])
          end
     end

     def cart 
        unless Cproduct.find_by(cust_id: session[:cid],status: "Cart").nil?
            @cproduct=Cproduct.where(cust_id: session[:cid],status: "Cart")
            @state=true
        else
            @state=false
        end
     end

     def edit
        p params[:id]
        @cproduct=Cproduct.find_by(pid: params[:id],cust_id: session[:cid],status: "Cart")
     end

     def update
         @cproduct = Cproduct.find_by(pid: params[:id],cust_id: session[:cid],status: "Cart")
       
         if @cproduct.update(product_creds)
           redirect_to cart_path,notice: "Cart successfully updated"
         else
            render 'edit',notice: "Update Failed"
         end
     end
     
     def destroy
         @cproduct = Cproduct.find_by(pid: params[:id],cust_id: session[:cid],status: "Cart")
         @cproduct.destroy
            redirect_to cart_url,notice: "Successfully Removed"
     end

     def payment
        @cproduct = Cproduct.where(cust_id: session[:cid])
        @count=0
        @cproduct.each do
            @count+=1
        end
        @tot_price=params[:tot_price]
        @tot_quantity=params[:tot_quantity]
     end

     
     private
     def product_creds
        params.require(:cproduct).permit(:pid,:pname,:quantity)
     end
end

 # #   @cproduct.cust_id=session[:cid]
        #  p"========================="
        #   p @cproduct
        #   p product_creds
        #   p"========================="
        #   @cproduct.quantity=params[:cproduct][:quantity]
        #   @cproduct.save
        #   p @cproduct.update_attributes(quantity: params[:cproduct][:quantity])
        # sql = "select product_name,pid,price from mproducts where quantity> 30"
        # raw = ActiveRecord::Base.connection.execute(sql)
        # raw.each do |row|
        #     puts row#.inspect # row is hash, something like {"name" => "Tom", "age" => 28}
        #   end
        # @pid=params[:pid]
        # sql = "Insert into Cproducts (pid,pname) product_name,pid,price from mproducts where quantity> 30"
        # raw = ActiveRecord::Base.connection.execute(sql)

        # @cart=Cproduct.new(product_creds)
    #     p params[:param1]
    # # session[:group] = params[:mproducts][:group]

# <% @search.each do |p|%>
#     <div class="col-sm-3 ">
#         <div class="container-fluid bg-info ">
#             <h3 class="text-center"><%=%></h3>
#             <br/>
#             <h5 class="text-left ">Price : &#8377;<%=p.price%></h5>
#             <h5 class="text-right ">Ratings : &#10031;<%=p.ratings%>no</h5>
#             <h5 class="text-left col-sm-8">Manufacturer : <%=p.product_id%> <%=product.find(p.product_id).username%> </h5>
#            <!-- <% @pid =p.id; %>  -->
#            <%= link_to "Add to cart",new_cproduct_path(param1: @pid),class: "btn btn-primary col-sm-4"%>
#             <h5 class="text-left col-sm-7">Available : <%=p.quantity%></h5>
        # <%= link_to "Add to cart",cproducts_path(pid: p.pid),method: :post,class: "btn btn-primary col-sm-5"%>
            
#         </div>
#     </div>
    
#     <% end%>
    

# <%= link_to "Edit" ,edit_product_path(session[:mid]),class: "btn btn-primary"%>

app/helpers/cproducts_helper.rb
module CproductsHelper
end

app/views/cproducts/cart.html.erb
<div class="container-fluid ">
    <br>
    <%= link_to "Home" , custs_path , class:"btn btn-info"%>
    <%= link_to 'Logout',mlogout_path ,class: "btn btn-danger",data:{confirm:"confirm to logout!!!"}%>
    <% if @state%>
    <h2>Your Cart Products</h2>

    <style>
    
        td,th {
        text-align: center;
        }
    </style>
    <%# p "@mproduct #{@mproduct.nil?}"%>
    <table class="table align-middled">
        <tr>
            <th>Product Id</th>
            <th>Product Group</th>
            <th>Product Name</th>
            <th>Manufacturer Id</th>
            <th>Manufacturer Name</th>
            <th>Quantity</th>
            <th>MRP</th>
            <th>Price</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        <% tot_price=0
        tot_quantity=0%>
        <% @cproduct.each do |mp| %>
        <% product=Mproduct.find_by(pid: mp.pid)
            #p product
           mfr=Mfr.find_by(id: product.mfr_id)
           %>
            <tr>
                <td><%= product.pid %></td>
                <td><%= product.group %></td>
                <td><%= product.product_name %></td>
                <td><%= mfr.id %></td> 
                <td><%= mfr.username %>,id <%= mp.cust_id %></td> 
                <td><%= mp.quantity %></td>
                <td><%= product.price %></td>
                <% price=mp.quantity*product.price%>
                <td><%= price %></td>
                <% tot_quantity+=mp.quantity
                 tot_price+=price%>
                <td><%= link_to "Edit",edit_cproduct_path(product.pid),class: "btn btn-primary"%></td>
                <td><%= link_to "Delete",cproduct_path(mp.pid),method: :delete,class: "btn btn-danger"%></td>
            </tr>
        <% end %>
    </table>
    <h3>Total Price is <%= tot_price%>
    <br/>
    <%= link_to "Order",payment_path(tot_price:tot_price,tot_quantity:tot_quantity),class: "btn btn-primary"%>
    <% else %>
        <h2>Your Cart Is Empty</h2>
    <%end%>
</div>

app/views/cproducts/edit.html.erb
<% content_for(:htmltitle,"Add to cart")%>
<h2>Add to cart</h2>

<%= form_for @cproduct,url: cproduct_path(params[:id]),method: :patch do |f| %>
<%@cproduct.errors.full_messages.each do |msg|%>
 <div class="alert alert-danger "><%=msg%></div>
<%end%>
	<div class="form-group ">	
		<div class="col-xs-2">
			<%= f.label :product_Id %>
		</div>
		<div class="col-xs-2">
			<%= params[:id]%>
			<%= f.hidden_field :pid, :value=> params[:id]%></td>

		</div>
	</div>
	<br/>
	<br/>
	<div class="form-group">
		<div class="col-xs-2">
			<%= f.label :product_name %>
		</div>
		<div class="col-xs-2">
        <% pname=Mproduct.find(params[:id]).product_name%>
        <%= pname%>
			<%= f.hidden_field :pname, :value=>pname%></td>
		</div>
	</div>
    <br/>
    <div class="form-group ">	
		<div class="col-xs-2">
			<%= f.label :"price__(per_kg)" %>
		</div>
		<div class="col-xs-2">
			<%= Mproduct.find(session[:pid]).price %>
			</div>
	</div>
    <br/>
    <div class="form-group ">	
		<div class="col-xs-2">
			<%= f.label :quantity %>
		</div>
		<div class="col-xs-2">
			<%= f.number_field :quantity ,value: Cproduct.find_by(pid: params[:id],cust_id: session[:cid]).quantity,min: 20,step: 10 ,class:"form-control "%>
		</div>
	</div>
	<br/>
    <br/>
	<div class="col-xs-2">
		<%= f.submit 'Update Cart' ,class: "btn btn-primary "%>
		<%= link_to "cancel" ,cart_path,class: "btn btn-primary"%>
	</div>
<%end%>
<br/>
<br/>

app/views/cproducts/index.html.erb
<h2> Product  </h2>

<table class="table ">
    <tbody>
    <tr class="">
      <th class="col-sm-1">Product Id</th>
      <td class="col-sm-1"><%= @product.pid %></td>
    </tr>
     <tr class="">
      <th class="col-sm-1">Product Name</th>
      <td class="col-sm-1"><%= @product.product_name %></td>
    </tr>
     <tr class="">
      <th class="col-sm-1">Quantity</th>
      <td class="col-sm-1"><%= @product.quantity %></td>
    </tr>
    <tr class="">
      <th class="col-sm-1">Price</th>
      <td class="col-sm-1"><%= @product.price %></td>
    </tr>
    <tr class="">
      <th class="col-sm-1">Manufacturer</th>
      <td class="col-sm-1"><%= Mfr.find(@product.mfr_id).username %></td>
    </tr>
    <tr class="">
      <th class="col-sm-1">Ratings</th>
      <td class="col-sm-1"><%= "%.3f" % [@product.ratings/@product.rcount.to_f] %></td>
    </tr>
    <tr>
        <th class="text-right">Rate the Product</th>
        <td class="col-sm-1">
            <%= link_to "1" ,ratings_path(mid:params[:mid],pid:params[:pid],number: 1)%>
            <%= link_to "2" ,ratings_path(mid:params[:mid],pid:params[:pid],number: 2)%>
            <%= link_to "3" ,ratings_path(mid:params[:mid],pid:params[:pid],number: 3)%>
            <%= link_to "4" ,ratings_path(mid:params[:mid],pid:params[:pid],number: 4)%>
            <%= link_to "5" ,ratings_path(mid:params[:mid],pid:params[:pid],number: 5)%>
        </td>
    </tr>
    </tbody>
</table>


<%= link_to 'Home',custs_path,class: "btn btn-primary"%>
<%= link_to 'Add to cart',new_cproduct_path(pid: @product.pid,pname:@product.product_name),class: "btn btn-primary"%>

<h2> Product from same Manufactures</h2>
<% @samemfr.each do |p|%>
<div class="col-sm-3 ">
    <div class="container-fluid bg-info ">
        <h3 class="text-center"><%=p.product_name%></h3>
        <br/>
        <h5 class="text-left col-sm-5">Price : &#8377;<%=p.price%></h5>
        <h5 class="text-right col-sm-7">Ratings : &#10031;<%=p.ratings%></h5>
        <h5 class="text-left col-sm-7">Available : <%=p.quantity%></h5>
        <%= link_to "View",cproducts_path(mid: p.mfr_id,pid: p.pid),class: "btn btn-primary col-sm-5"%> <h2 class="text-left col-sm-7"></h2>
        <%= link_to "Add to cart",new_cproduct_path(pid: p.pid,pname:p.product_name),class: "btn btn-primary col-sm-5 center"%>
        
    </div>
</div>

<% end%>




app/views/cproducts/new.html.erb
<% content_for(:htmltitle,"Add to cart")%>
<h2>Add to cart</h2>

<%= form_for @cart,url: cproducts_path(@cart) do |f| %>
<%@cart.errors.full_messages.each do |msg|%>
 <div class="alert alert-danger "><%=msg%></div>
<%end%>
	<div class="form-group ">	
		<div class="col-xs-2">
			<%= f.label :product_Id %>
		</div>
		<div class="col-xs-2">
			<%= session[:pid]%>
			<%= f.hidden_field :pid, :value=> session[:pid]%></td>

		</div>
	</div>
	<br/>
	<br/>
	<div class="form-group">
		<div class="col-xs-2">
			<%= f.label :product_name %>
		</div>
		<div class="col-xs-2">
        <%= session[:pname]%>
			<%= f.hidden_field :pname, :value=>session[:pname]%></td>
		</div>
	</div>
    <br/>
	<br/>
	<div class="form-group ">	
		<div class="col-xs-2">
			<%= f.label :"price__(per_kg)" %>
		</div>
		<div class="col-xs-2">
			<%= Mproduct.find(session[:pid]).price %>
			</div>
	</div>
    <br/>
    <div class="form-group ">	
		<div class="col-xs-2">
			<%= f.label :quantity %>
		</div>
		<div class="col-xs-2">
			<%= f.number_field :quantity,value: 20,min:20,step: 10 ,class:"form-control "%>
		</div>
	</div>
	<br/>
    <br/>
	<div class="col-xs-2">
		<%= f.submit 'Save' ,class: "btn btn-primary "%>
		<%= link_to "cancel" ,custs_path,class: "btn btn-primary"%>
	</div>
<%end%>
<br/>
<br/>

app/views/cproducts/payment.html.erb
<div class="container-fluid">
<h1>Payment Gateway</h1>

<h3> Total no of Products : <%= @count%> </h3>
<br/>
<h3> Total Quantity : <%= @tot_quantity%> Kg </h3>
<br/>
<h3> Total Price : &#8377; <%= @tot_price%> </h3>
<br/>
<%= link_to "Place Order",orders_confirm_path(tot_price: @tot_price),class: "btn btn-primary"%>
<%= link_to "cancel",:back,class: "btn btn-primary"%>
</div>