config/routes.rb
Rails.application.routes.draw do

  root 'goodsmarkets#index'
  get 'goodsmarkets/index'
  get 'goodsmarkets/customer'
  post '/csignin'=>'goodsmarkets#csignin', as: 'csignin'
  get 'goodsmarkets/manufacturer'
  post '/msignin'=>'goodsmarkets#msignin',  as: 'msignin'
  get 'mfrs/logout'=>'mfrs#logout', as: 'mlogout'
  get 'mfrs/profile'=>'mfrs#profile', as: 'mprofile'
  get 'custs/logout'=>'custs#logout', as: 'clogout'
  get 'custs/profile'=>'custs#profile', as: 'cprofile'
  post 'custs/search'=>'custs#search', as: 'search'
  get 'cproducts/ratings'=>'cproducts#ratings',as:'ratings'
  get 'cproducts/cart'=>'cproducts#cart',as:'cart'
  get 'cproducts/payment'=>'cproducts#payment',as:'payment'
  get 'cproducts/order'=>'cproducts#order',as:'order'
  get 'orders/confirm'=>'orders#confirm'
  get 'orders/cancel'=>'orders#cancel'
  get 'orders/show'=>'orders#show'
  get 'orders/shipped'=>'orders#shipped'
  get 'orders/delivered'=>'orders#delivered'
  get 'orders/packed'=>'orders#packed'
  get 'orders/forcecancel'=>'orders#forcecancel'
  # get 'mhomes/logout'=>'mhomes#logout', as: 'mlogout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :mfrs do
    resources :mproducts
  end
  resources :custs
  resources :cproducts
#   if Rails.env.production?
#     get '404', :to => 'application#page_not_found'
#  end
end

app/controllers/goodsmarkets_controller.rb
class GoodsmarketsController < ApplicationController
  skip_before_action :verify_login

  def index
  end

  def customer
    if session[:cid]
      redirect_to custs_path
    else
      @cust=Cust.new
    end
  end

  def csignin
   @cust=Cust.new(cust_credentials)  
    cust=Cust.find_by(email: @cust.email,password: @cust.password)
    unless cust.nil?
      session[:cid]=cust.id
      redirect_to custs_path
    else
      redirect_to :back,alert: "Invalid Username or Password"
    end
  end

  def manufacturer
    # session[:mid]=1
    if session[:mid]
      redirect_to mfrs_path
    else
      @mfr=Mfr.new
    end
  end

  def msignin
    @mfr=Mfr.new(mfr_credentials)
    mfr=Mfr.find_by(email: @mfr.email,password: @mfr.password)
    unless mfr.nil?
      session[:mid] = mfr.id
     	redirect_to mfrs_path
    else 
      # render 'manufacturer'
      redirect_to :back,alert: "Invalid Username or Password"
    end
  end
  private
  def cust_credentials
    params.require(:cust).permit(:email,:password)
  end
  def mfr_credentials
    params.require(:mfr).permit(:email,:password)
  end
end



=begin
  p "================================="
 p "*****************************"
      #@msign=Goodsmarket.new(msign_params)
      #mfr=Mfr.find_by(email: params[:Goodsmarket][:email])
      p mfr
      puts"========================================================================#{session[:email]}"
    # if mfr#.authenticate(password: @mfr.password)
  	#if mfr#.password==(params [:goodsmarket][:password])
  	 # manufacturer
      #  render 'manufacturer'
      # render 'goodsmarkets_manufacturer_path'
   #if session[:cemail]
    #  redirect_to new_chome_path
    #else
    ##  @cst=Mfr.new
    #end#redirect_to chomes
=end

app/helpers/goodsmarkets_helper.rb
module GoodsmarketsHelper

end

app/views/goodsmarkets/customer.html.erb
<h1> Welcome Customers </h1>

<% content_for(:htmltitle,"Customer login")%>
<br>
<%= form_for @cust,url: csignin_path  do |f| %>
<% if flash[:alert]%>
<div class="alert alert-danger "><%= flash[:alert] %></div>
<% end%>
	<div class="form-group ">	
		<div class="col-xs-1">
			<%= f.label :email %>
		</div>
		<div class="col-xs-2">
			<%= f.text_field :email ,class:"form-control "%>
		</div>
	</div>
	<br/>
	<br/>
	<div class="form-group">
		<div class="col-xs-1">
		<%= f.label :password %>
			</div>
		<div class="col-xs-2">
			<%= f.text_field :password ,class:"form-control mb-3"%></td>
		</div>
	</div>
	<br/><br/>
	<div class="col-xs-1">
		<%= f.submit 'login' ,class: "btn btn-primary "%>    
	</div>
	<%= link_to 'cancel',root_path ,class: "btn btn-primary"%>
<%end%>
<br/>
<p class="h4">New User .........
<%= link_to 'Customer Signup',new_cust_path ,class: "btn btn-primary"%>
</p>

app/views/goodsmarkets/index.html.erb
<h1 style="color: blue;">Welcome to Goods Market</h1>

<div class= "container-fluid pt-3">
<p style="font-size: 20px;">B2B e-commerce, short for business-to-business electronic commerce, is the sale of goods or services between businesses via an online sales portal. In general, it is used to improve the efficiency and effectiveness of a company's sales efforts. Instead of receiving orders using human assets (sales reps) manually – by telephone or e-mail – orders are received digitally, reducing overhead costs.</p>
<br>

<h3>
	<%= link_to 'Shopkeepers login',goodsmarkets_customer_path ,class: "btn btn-primary"%>
</h3>
<br>
<h3>
	<%= link_to 'Manufacturers login',goodsmarkets_manufacturer_path ,class: "btn btn-primary"%>
</h3>
</div>

app/views/goodsmarkets/manufacturer.html.erb
<h1> Welcome Manufacturer </h1>
<% content_for(:htmltitle,"Manufacturer login")%>
<br>
<%= form_for @mfr,url: msignin_path  do |f| %>
<% if flash[:alert]%>
<div class="alert alert-danger "><%= flash[:alert] %></div>
<% end%>
	<div class="form-group ">	
		<div class="col-xs-1">
			<%= f.label :email %>
		</div>
		<div class="col-xs-2">
			<%= f.text_field :email ,class:"form-control "%>
		</div>
	</div>
	<br/>
	<br/>
	<div class="form-group">
		<div class="col-xs-1">
		<%= f.label :password %>
			</div>
		<div class="col-xs-2">
			<%= f.text_field :password ,class:"form-control mb-3"%></td>
		</div>
	</div>
	<br/><br/>
	<div class="col-xs-1">
		<%= f.submit 'login' ,class: "btn btn-primary "%>    
	</div>
	<%= link_to 'cancel',root_path ,class: "btn btn-primary"%>
<%end%>
<br/>
<p class="h4">New User .........
<%= link_to 'Manufacturers Signup',new_mfr_path ,class: "btn btn-primary"%>
</p>