config/routes.rb
Rails.application.routes.draw do

  root 'goodsmarkets#index'
  get 'goodsmarkets/index'
  get 'goodsmarkets/customer'
  post '/csignin'=>'goodsmarkets#csignin', as: 'csignin'
  get 'goodsmarkets/manufacturer'
  post '/msignin'=>'goodsmarkets#msignin',  as: 'msignin'
  get 'mfrs/logout'=>'mfrs#logout', as: 'mlogout'
  get 'mfrs/profile'=>'mfrs#profile', as: 'mprofile'
  get 'custs/logout'=>'custs#logout', as: 'clogout'
  get 'custs/profile'=>'custs#profile', as: 'cprofile'
  post 'custs/search'=>'custs#search', as: 'search'
  get 'cproducts/ratings'=>'cproducts#ratings',as:'ratings'
  get 'cproducts/cart'=>'cproducts#cart',as:'cart'
  get 'cproducts/payment'=>'cproducts#payment',as:'payment'
  get 'cproducts/order'=>'cproducts#order',as:'order'
  get 'orders/confirm'=>'orders#confirm'
  get 'orders/cancel'=>'orders#cancel'
  get 'orders/show'=>'orders#show'
  get 'orders/shipped'=>'orders#shipped'
  get 'orders/delivered'=>'orders#delivered'
  get 'orders/packed'=>'orders#packed'
  get 'orders/forcecancel'=>'orders#forcecancel'
  # get 'mhomes/logout'=>'mhomes#logout', as: 'mlogout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :mfrs do
    resources :mproducts
  end
  resources :custs
  resources :cproducts
#   if Rails.env.production?
#     get '404', :to => 'application#page_not_found'
#  end
end

app/models/mfr.rb
class Mfr < ApplicationRecord
    has_many :mproducts
    validates :username ,presence: true
    validates :email ,presence: true,uniqueness: true,format: { with: /\A[A-Za-z][A-Za-z0-9]+@[A-Za-z0-9]+\.[a-z]{2,3}\z/ }
    validates :password ,presence: true,length: {in: 6..10}
    validates :mobile_no ,presence: true ,numericality: {only_integer: true},length: {is: 10}
end

app/controllers/mfrs_controller.rb
class MfrsController < ApplicationController
	skip_before_filter :verify_login ,only: [:new,:create]
	def index 
		@mfr=Mfr.find(session[:mid])
		unless params[:status].nil?
			sql=ActiveRecord::Base.connection.raw_connection.prepare("select c.id,c.pid,c.pname,c.quantity,cu.id,cu.username,cu.address,cu.mobile_no,c.status from cproducts as c,custs as cu,mproducts as mp where mp.mfr_id = ? and mp.pid=c.pid and c.cust_id=cu.id and c.status = ? order by c.id ASC;")
			@out=sql.execute(session[:mid],params[:status])
		else
			sql=ActiveRecord::Base.connection.raw_connection.prepare("select c.id,c.pid,c.pname,c.quantity,cu.id,cu.username,cu.address,cu.mobile_no,c.status from cproducts as c,custs as cu,mproducts as mp where mp.mfr_id = ? and mp.pid=c.pid and c.cust_id=cu.id and c.status!='Cart' order by c.id ASC;")
			@out=sql.execute(session[:mid])
		end
	end
	def new
		@mfr=Mfr.new
	end
	def create
		@mfr=Mfr.new(mfr_params)
		if @mfr.save
			session[:mid]=Mfr.find_by(email: @mfr.email,password: @mfr.password).id
			p session[:mid]
			redirect_to mfrs_path
		else
			render 'new'
		end
	end

	def edit
		@mfr=Mfr.find(session[:mid])
	end

	def update
		@mfr=Mfr.find(session[:mid])
		if @mfr.update(mfr_params)
			redirect_to mprofile_path
		else
			render 'edit'
		end
	end	
	def profile
		@mfr=Mfr.find(session[:mid])
	end
	def logout
		session.delete(:mid)
		redirect_to root_path
	   end
	def destroy 
		@mfr=Mfr.find(session[:mid])
		@mfr.destroy
		logout
	end
	private
	def mfr_params
		params.require(:mfr).permit(:username,:email,:password,:mobile_no)
	end
end

# @mfr=Mfr.find(session[:mid])
# 		unless params[:status].nil?
# 		sql="select c.id,c.pid,c.pname,c.quantity,cu.id,cu.username,cu.address,cu.mobile_no,c.status from cproducts as c,custs as
# 		 cu,mproducts as mp where mp.mfr_id=#{session[:mid]} and mp.pid=c.pid and c.cust_id=cu.id and c.status='#{params[:status]}' order by c.id ASC;"
# 		else
# 		sql="select c.id,c.pid,c.pname,c.quantity,cu.id,cu.username,cu.address,cu.mobile_no,c.status from cproducts as c,custs as
# 		 cu,mproducts as mp where mp.mfr_id=#{session[:mid]} and mp.pid=c.pid and c.cust_id=cu.id and c.status!='Cart' order by c.id ASC;"
# 		end
# 		@out=ActiveRecord::Base.connection.execute(sql)

app/helpers/mfrs_helper.rb
module MfrsHelper
end

app/views/mfrs/edit.html.erb
<% content_for(:htmltitle,"Edit Profile")%>
<h2>Edit your Profile</h2>

<%= form_for :mfr,url: mfr_path(@mfr) ,method: :patch do |f| %>
<%@mfr.errors.full_messages.each do |msg|%>
 <div class="alert alert-danger "><%=msg%></div>
<%end%>
	<div class="form-group ">	
		<div class="col-xs-1">
			<%= f.label :username %>
		</div>
		<div class="col-xs-2">
			<%= f.text_field :username ,class:"form-control "%>
		</div>
	</div>
	<br/>
	<br/>
	<div class="form-group">
		<div class="col-xs-1">
			<%= f.label :email %>
		</div>
		<div class="col-xs-2">
			<%= f.text_field :email ,class:"form-control"%></td>
		</div>
	</div>
	<br/>
    <div class="form-group ">	
		<div class="col-xs-1">
			<%= f.label :password %>
		</div>
		<div class="col-xs-2">
			<%= f.text_field :password ,class:"form-control "%>
		</div>
	</div>
	<br/>
	<div class="form-group">
		<div class="col-xs-1">
			<%= f.label :mobile_no %>
		</div>
		<div class="col-xs-2">
			<%= f.text_field :mobile_no ,class:"form-control "%></td>
		</div>
	</div>
	<br/>
	<br/>
	<div class="col-xs-2">
		<%= f.submit 'Save' ,class: "btn btn-primary "%>
		<%= link_to "cancel" ,mprofile_path,class: "btn btn-primary"%>
	</div>
<%end%>
<br/>
<br/>

app/views/mfrs/index.html.erb
<h1> Welcome <%= @mfr.username%></h1>
<br>
<div class="container-fluid ">
    <%= link_to "Home" , mfrs_path , class:"btn btn-info"%>
    <%= link_to "Profile" , mprofile_path , class:"btn btn-info"%>
    <%= link_to 'Products',mfr_mproducts_path(@mid), class:"btn btn-info"%>
    <%= link_to 'Logout',mlogout_path ,class: "btn btn-danger",data:{confirm:"confirm to logout!!!"}%>
    <style>
        div a {color: black;
            text-decoration: none;
            background-color: #f6f6f6;
            border: 1px solid #ddd;
            padding: 12px 16px;
            z-index: -1;
            display: block;"}
        a{
            min-width: 20px;
            position: absolute;
            overflow: auto;
            width: 100px;
        }
    </style>
    <br/><br/>
    <div class="dropdown">
        <button class="btn btn-primary" type="button"onclick="document.getElementById('dropdown-menu').classList.toggle('show')">Sort By Status
            <span class="caret"></span>
        </button>
        
        <div id="dropdown-menu" style="display:none;width: 160px;">
            <a href="<%=mfrs_path(status:"Placed")%>">Placed</a>
            <a href="<%=mfrs_path(status:"Packed")%>">Packed</a>
            <a href="<%=mfrs_path(status:"Shipped")%>">Shipped</a>
            <a href="<%=mfrs_path(status:"Delivered")%>">Delivered</a>
            <a href="<%=mfrs_path(status:"Force Cancelled")%>">Force Cancelled</a>
            <a href="<%=mfrs_path%>">All</a>
        </div>
    </div>
</div>


<h1><%= params[:status]? params[:status] : "All"%> Orders </h1>
<br/>
<br/>
<div class="container-fluid ">
    <style>
    td,th {
        text-align: center;
        }
    </style>
    <table class="table align-middled">
        <tr>
            <th>Order Id</th>
            <th>Product Id</th>
            <th>Product Name</th>
            <th>Quantity</th>
            <th>Customer Id</th>
            <th>Customer Name</th>
            <th>Address</th>
            <th>mobile no</th>
            <th>status</th>
            <th>Edit</th>
        </tr>
        <% @out.each do |p| %>
            <tr>
                <td><%= p[0] %></th>
                <td><%= p[1] %></td>
                <td><%= p[2] %></td>
                <td><%= p[3] %></td>
                <td><%= p[4] %></td>
                <td><%= p[5] %></td>
                <td><%= p[6] %></td>
                <td><%= p[7] %></td>
                <td><%= p[8] %></td>
                <td>
                    <% if p[8]=="Placed"||p[8]=="Packed"%>
                            <button class="btn btn-primary" type="button" onclick="document.getElementById('<%=p[0]%>').classList.toggle('show')">Change Status
                            <span class="caret"></span>
                            </button>
                            <div id="<%=p[0]%>" style="display:none;width: 200px;">
                        <% case p[8]

                        when "Placed"%>
                            <a href="<%=orders_packed_path(id:p[0])%>">Change to Packed</a>
                            <a href="<%=orders_shipped_path(id:p[0])%>">Change to Shipped</a>
                            <a href="<%=orders_delivered_path(id:p[0])%>">Change to Delivered</a>
                            <a href="<%=orders_forcecancel_path(id:p[0])%>">Force Cancel</a>
                        <% when "Packed" %>
                            <a href="<%=orders_shipped_path(id:p[0])%>">Change to Shipped</a>
                            <a href="<%=orders_delivered_path(id:p[0])%>">Change to Delivered</a>
                            <a href="<%=orders_forcecancel_path(id:p[0])%>">Force Cancel</a>
                        <% end%>
                    <%elsif p[8]=="Shipped"%>
                        <%=link_to "Change to Delivered",orders_delivered_path(id:p[0]),class: "btn btn-primary"%>
                    <% else%>
                        -
                    <%end%>
                </td>
            </tr>
        <% end %>
    </table>
</div>

app/views/mfrs/new.html.erb
<h2> Welcome New Manufacturer </h2>

<%= form_for :mfr, url: mfrs_path do |f| %>
<%@mfr.errors.full_messages.each do |msg|%>
 <div class="alert alert-danger "><%=msg%></div>
<%end%>
<div class="form-group ">	
		<div class="col-xs-1">
			<%= f.label :username %>
		</div>
		<div class="col-xs-2">
			<%= f.text_field :username ,class:"form-control "%>
		</div>
	</div>
	<br/>
	<br/>
	<div class="form-group">
		<div class="col-xs-1">
			<%= f.label :email %>
		</div>
		<div class="col-xs-2">
			<%= f.text_field :email ,class:"form-control"%></td>
		</div>
	</div>
	<br/>
    <div class="form-group ">	
		<div class="col-xs-1">
			<%= f.label :password %>
		</div>
		<div class="col-xs-2">
			<%= f.text_field :password ,class:"form-control "%>
		</div>
	</div>
	<br/>
	<div class="form-group">
		<div class="col-xs-1">
			<%= f.label :mobile_no %>
		</div>
		<div class="col-xs-2">
			<%= f.text_field :mobile_no ,class:"form-control "%></td>
		</div>
	</div>
	<br/>
	<br/>
	<div class="col-xs-2">
		<%= f.submit 'Save' ,class: "btn btn-primary "%>
		<%= link_to "cancel" ,goodsmarkets_manufacturer_path,class: "btn btn-primary"%>
</div>
	<%end%>

app/views/mfrs/profile.html.erb
<h2>Profile</h2>

<table class="table">
    <tbody>
    <tr class="">
      <th class="col-sm-1">Username</th>
      <td class="col-sm-1"><%= @mfr.username %></td>
    </tr>
     <tr class="">
      <th class="col-sm-1">Email id</th>
      <td class="col-sm-1"><%= @mfr.email %></td>
    </tr>
     <tr class="">
      <th class="col-sm-1">Mobile number</th>
      <td class="col-sm-1"><%= @mfr.mobile_no %></td>
    </tr>
    </tbody>
</table>


<%= link_to "Edit" ,edit_mfr_path(session[:mid]),class: "btn btn-primary"%>
<%= link_to 'Home',mfrs_path ,class: "btn btn-primary"%>

<%= link_to "Delete Account" ,mfr_path(session[:mid]),method: :delete,data:{confirm:"confirm to Delete Account \n once Deleted it cant be retrived!!!!!"},class: "btn btn-danger"%>